### ISSUE TITLE
Zizzania handshake throws the error `TypeError: expected str, bytes or os.PathLike object, not NoneType`

### ISSUE THREAD

**Issue by 1mehdifaraji** [cyrus-and/zizzania#16]
Mac M1 Ventura 13.3.1

```
Initiating zizzania to capture handshake...

Traceback (most recent call last):
  File "/Users/mehdi/Desktop/WiFiCrackPy/WiFiCrackPy.py", line 159, in <module>
    scan_networks()
  File "/Users/mehdi/Desktop/WiFiCrackPy/WiFiCrackPy.py", line 99, in scan_networks
    capture_network(networks_sorted[x]['bssid'], networks_sorted[x]['channel_object'])
  File "/Users/mehdi/Desktop/WiFiCrackPy/WiFiCrackPy.py", line 118, in capture_network
    subprocess.run(['sudo', zizzania_path, '-i', iface, '-b', bssid, '-w', 'capture.pcap', '-q'] + ['-n'] * args.d)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by cyrus-and** [comment]
Ehm, this is not a Python project...

**Comment by 1mehdifaraji** [comment]
Fixed the issue with changing installed python version from `3.9.6` to `3.9.13`.
